[package]
name = "bevy-chess"
version = "0.1.0"
authors = ["hmatt1 <hornung.m1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.3"
bevy_mod_picking = "0.2.0"